---
title: "Data import"
author: "Cesar"
date: "14/4/2020"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---
# Setup work directory
---

```{r}
setwd(getwd())
dir()
```

---
# Setup path
This setup is done to work in diferentes s.o
---

```{r}
setwd(getwd())
file_txt <- file.path("datasetS", "dataset_provincias1.txt")
raw_data <- read.delim(file_txt, stringsAsFactors = FALSE)
str(raw_data)
```

---
# Setup separator with read table
read table is a general method.
---

```{r}
setwd(getwd())
path_file <- file.path("datasetS", "dataset_provincias2.txt")
raw_data <- read.table(path_file, stringsAsFactors = FALSE, header = TRUE, sep = "/")
str(raw_data)
```

---
# Read CSV Y CSV2
---

```{r}
setwd(getwd())
path_file <- file.path("datasetS", "dataset_provincias3.csv")
raw_data <- read.csv(path_file, stringsAsFactors = FALSE)
str(raw_data)
```

```{r}
setwd(getwd())
path_file <- file.path("datasetS", "dataset_provincias4.csv")
raw_data <- read.csv2(path_file, stringsAsFactors = FALSE)
str(raw_data)
```

---
# Cast loading
---

```{r}
setwd(getwd())
path_file <- file.path("datasetS", "dataset_provincias1.txt")
raw_data <- read.delim(path_file, stringsAsFactors = FALSE, colClasses = c("character", "numeric", "character", "NULL", "NULL", "NULL"))
str(raw_data)
```

---
Read Excel
---

```{r}
library(readxl)

setwd(getwd())
file_excel <- file.path("datasetS", "dataset_provincias5.xlsx")

excel_sheets(file_excel)
```

```{r}
poblacion <- read_excel(file_excel, sheet = 1)
superficie <- read_excel(file_excel, sheet = "superficie")

str(poblacion)
str(superficie)
```

```{r}
provincias_unificado2 <- cbind(poblacion, superficie[-1])
str(provincias_unificado2)
```

---
Read Json
---

```{r}
library(jsonlite)
fromJSON("http://url")
```